$: s("tb tb tb tb".early(1 / 8)).bank("sr16").degradeBy(.5)
$: s("bd bd bd bd").bank("tr909").sometimes(ply(2))
$: s("sh [sh sh] sh [sh sh]").bank("tr808").almostNever(ply(4)).hpf(2000)
_$: s("mt mt lt ht").bank("tr909").fast(2).lpf(200)
$: "<c4 d4>".note().s("gm_pad_new_age:2").room(.2)
    .hpf(500).roomsize(1.5).postgain(1.5)
$: note("e4".add.squeeze(rand.range(0, 8).seg(8).floor()))
    .degradeBy(.25).rib(0, 4).s("dark_organ:0").dec(1).postgain(1)
    .hpf(2000)
    ._punchcard()
$CTL: s("square").note("-48").bus(1).dry(0)._scope()
$: note("e#4").s("gm_choir_aahs")
    // .vowel("o")
    .att(.5).dec(.2).sus(.9).rel(1)
    .delay(.1)
    .lpf(2000)
    .hpf(500)
    .postgain(2).bmod({ b: 1 })._scope()